name: Tests

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs:

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29

  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: make test

  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: '1.14'
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: make test
