name: Tests

on: [ push ]

jobs:

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.28

    - name: Staticcheck
      run: |
        go get honnef.co/go/tools/cmd/staticcheck
        export PATH=${PATH}:`go env GOPATH`/bin
        make staticcheck

  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: make test

  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: make test
