name: Tests

on: [ push, pull_request ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Get staticcheck
      run: go get -v honnef.co/go/tools/cmd/staticcheck

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./...

    - name: Run staticcheck
      run: staticcheck ./...
