name: Tests

on: [ push ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8

    - name: Install staticcheck
      run: go get honnef.co/go/tools/cmd/staticcheck

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: make test
